/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface SupersedeParagraph {
    'last': string;
    'textblock': string;
    'userid': string;
  }
}

declare global {


  interface HTMLSupersedeParagraphElement extends Components.SupersedeParagraph, HTMLStencilElement {}
  var HTMLSupersedeParagraphElement: {
    prototype: HTMLSupersedeParagraphElement;
    new (): HTMLSupersedeParagraphElement;
  };
  interface HTMLElementTagNameMap {
    'supersede-paragraph': HTMLSupersedeParagraphElement;
  }
}

declare namespace LocalJSX {
  interface SupersedeParagraph extends JSXBase.HTMLAttributes<HTMLSupersedeParagraphElement> {
    'last'?: string;
    'textblock'?: string;
    'userid'?: string;
  }

  interface IntrinsicElements {
    'supersede-paragraph': SupersedeParagraph;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


