/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface SupersedeH1 {
    'cls': string;
    'path': string;
    'snippetname': string;
    'userid': string;
  }
  interface SupersedeH2 {
    'cls': string;
    'path': string;
    'snippetname': string;
    'userid': string;
  }
  interface SupersedeParagraph {
    'cls': string;
    'path': string;
    'snippetname': string;
    'userid': string;
  }
}

declare global {


  interface HTMLSupersedeH1Element extends Components.SupersedeH1, HTMLStencilElement {}
  var HTMLSupersedeH1Element: {
    prototype: HTMLSupersedeH1Element;
    new (): HTMLSupersedeH1Element;
  };

  interface HTMLSupersedeH2Element extends Components.SupersedeH2, HTMLStencilElement {}
  var HTMLSupersedeH2Element: {
    prototype: HTMLSupersedeH2Element;
    new (): HTMLSupersedeH2Element;
  };

  interface HTMLSupersedeParagraphElement extends Components.SupersedeParagraph, HTMLStencilElement {}
  var HTMLSupersedeParagraphElement: {
    prototype: HTMLSupersedeParagraphElement;
    new (): HTMLSupersedeParagraphElement;
  };
  interface HTMLElementTagNameMap {
    'supersede-h1': HTMLSupersedeH1Element;
    'supersede-h2': HTMLSupersedeH2Element;
    'supersede-paragraph': HTMLSupersedeParagraphElement;
  }
}

declare namespace LocalJSX {
  interface SupersedeH1 extends JSXBase.HTMLAttributes<HTMLSupersedeH1Element> {
    'cls'?: string;
    'path'?: string;
    'snippetname'?: string;
    'userid'?: string;
  }
  interface SupersedeH2 extends JSXBase.HTMLAttributes<HTMLSupersedeH2Element> {
    'cls'?: string;
    'path'?: string;
    'snippetname'?: string;
    'userid'?: string;
  }
  interface SupersedeParagraph extends JSXBase.HTMLAttributes<HTMLSupersedeParagraphElement> {
    'cls'?: string;
    'path'?: string;
    'snippetname'?: string;
    'userid'?: string;
  }

  interface IntrinsicElements {
    'supersede-h1': SupersedeH1;
    'supersede-h2': SupersedeH2;
    'supersede-paragraph': SupersedeParagraph;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


